### ISSUE TITLE
Consumes all CPU repeatedly polling for modified files. Will start a fire! 

### ISSUE THREAD

**Issue by bmenasha** [GoogleCloudPlatform/appstart#11] opened 2015-10-24 14:55 UTC
running 

> appstart run app.yaml

the dev_appserver.py container is consuming all the CPU and heating the world. 

It's constanly looping through:

google.appengine.tools.devappserver2.module.ExternalModule.handle_changes

This function returns immediately, but the outer loop "_loop_watching_for_changes"  clearly expects it to pause for the supplied number of milliseconds before returning. 

That it doesn't pause and immediately returns caused my poor laptop to fail due to thermal fault. 

Thanks for looking into it.

**Comment by mindhog** [comment] 2015-10-26 18:08
I'm able to reproduce this - it looks like devappserver is spinning.

I'll have to take a look at the devappserver code and see what's going on.

**Comment by mindhog** [comment] 2015-10-30 17:01
Fix in [2371ff](https://github.com/mindhog/appstart/commit/2371ff01d68a9c8a78431ad5a0f1231a2d5166c5), awaiting [PR/16](https://github.com/GoogleCloudPlatform/appstart/pull/16)

**Comment by mindhog** [comment] 2015-10-30 19:26
Merged with master.

**Closed as completed by mindhog** 2015-10-30 19:26 UTC
Labels: bug, P1
